### PR TITLE
Final draft of learning objective

### PR DESCRIPTION
**Pull request by cheng-cs**
This PR contains the final version of the learning objectives.

### CODE REVIEW

**Review by ColemanKobe — CHANGES_REQUESTED** [review]
Some learning objectives need to be revised, especially ones that have words like: recognize, describe, define, articulate, know, justify, etc. There needs to be a demonstration of understanding, not just understanding

**Review by ColemanKobe — APPROVED** [review]
lgtm

**Review by ColemanKobe — APPROVED** [review]
lgtm

**Review by burgess01 — DISMISSED** [review]

**Review by ColemanKobe — APPROVED** [review]
lgtm

**Pull request merged**
