### PR TITLE
Unify RAM in index file

### PR DESCRIPTION
**Pull request by Yanqiao4396**
Found there is usage of `Ram`, `ram` and  `Ram`. Unify them to RAM

### CODE REVIEW

**Review by burgess01 — COMMENTED** [review]
This looks good. You just need to pull main into your branch in order to get the most recent changes integrated into your PR and then I believe this is ready to merge. Thanks!

**Review by burgess01 — CHANGES_REQUESTED** [review]
It appears that the changes made in this PR are no longer relevant with the current state of main. I think that this PR would be best suited to be closed while your other PR is merged. I am saying this because if you go into the files changed there are now no longer any differing lines.

**Comment by gkapfham** [comment]
Hello @Yanqiao4396 do you agree that this PR can be closed?

If so, could I trouble you to please go ahead and close it? Thanks!

**Comment by Yanqiao4396** [comment]
Sure, I agree with it

**Pull request closed without merging**
