### PR TITLE
Add missing name to schedule

### PR DESCRIPTION
**Pull request by LiamBlack3**
I improved upon the course schedule page my assigning both Liam's names to the Network File Systems chapter.

### CODE REVIEW

**Review by burgess01 — COMMENTED** [review]
I think it could be a good idea to put a last name initial after both Liams in order to make it a bit more clear who is who. As it is it looks good, but someone could mistake it for being a typo of the same person's name twice. What do you think about this suggestion?

**Comment by LiamBlack3** [comment]
I totally agree Katie, I added our initials, thanks for the feedback!

**Review by burgess01 — DISMISSED** [review]
Thanks Liam! This looks great! I think its ready to merge now.

**Review by burgess01 — APPROVED** [review]
This looks great. Thank you for doing this Liam!

**Pull request merged**
